workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: Encrypted(...)
      node: 18.19.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          npx expo build:ios --type archive --non-interactive
    artifacts:
      - build/**/*.ipa
      - build/**/*.app
