name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build iOS with EAS
      run: |
        npm install -g @expo/eas-cli
        eas build --platform ios --profile app-store --non-interactive
        
    - name: Download build artifacts
      run: |
        eas build:list --platform ios --limit 1 --json > build-info.json
        cat build-info.json
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-info
        path: build-info.json